nomic-io/nomic

rust.yml
We should probably have this so we can easily see if we push broken commits.
=> Added GitHub action to build and test

Cargo.lock, Cargo.toml, core/signatory-set/Cargo.toml, core/signatory-set/src/error.rs, core/signatory-set/src/lib.rs, core/signatory-set/src/reserve_script.rs, core/signatory-set/src/signatory_set.rs, core/signatory-set/src/test_utils.rs
This adds the data types for signatory sets (with data structures optimized for the addition/removal of that set along with keeping them in sorted order by voting power).
It will also add a module which builds the reserve script.
=> Signatory sets

Cargo.lock, README.md, chain/chain/src/abci_server.rs, chain/chain/src/spv/error.rs, chain/chain/src/spv/headercache.rs, chain/chain/src/state_machine.rs, chain/client/src/client.rs, core/primitives/src/transaction.rs, core/signatory-set/src/lib.rs, core/signatory-set/src/reserve_script.rs, core/signatory-set/src/signatory_set.rs, relayer/Cargo.toml, relayer/src/relayer.rs, worker/Cargo.toml, worker/src/lib.rs
This PR changes some error handling (especially in the SPV module) and fixes all compiler / clippy warnings.
=> Fix warnings

Cargo.lock, chain/chain/src/spv/headercache.rs, chain/chain/src/state_machine.rs, chain/client/src/client.rs, core/primitives/Cargo.toml, core/primitives/src/error.rs, core/primitives/src/lib.rs, core/primitives/src/transaction.rs
This PR:
- Starts deposit transaction handling in the on-chain state machine
- Fixes a bug in the header cache
=> Deposit transactions and bug fixes

Cargo.lock, chain/chain/Cargo.toml, chain/chain/src/abci_server.rs, chain/chain/src/action.rs, chain/chain/src/state_machine.rs, chain/client/Cargo.toml, chain/client/src/client.rs, cli/Cargo.toml, cli/src/main.rs, cli/src/tendermint.rs, core/primitives/src/transaction.rs, core/signatory-set/Cargo.toml, core/signatory-set/src/reserve_script.rs, core/signatory-set/src/signatory_set.rs, relayer/Cargo.toml, relayer/src/deposit.rs, relayer/src/error.rs, relayer/src/lib.rs, relayer/src/relayer.rs
After this PR, the relayer scans Bitcoin for deposits to the network's reserve script and relays them to the sidechain.
Not finished yet: bitcoind rescanning / importaddress life cycle, that'll come in the next PR.
=> Relayer deposits

Cargo.lock
This updates orga to include stability improvements based on something found recently on the testnet.
=> Upgrade orga dependency

rest/src/main.rs, src/bin/nomic.rs
Added tendermint-style routes to some REST queries and added more fields to validator cmd
=> Updated some REST queries and validators cmd

README.md
Completed the testnet readme to show the right set of commands, making onboarding new nodes easier.
=> Testnet readme

Cargo.lock, Cargo.toml, src/airdrop.rs, src/app.rs, src/app/migrations.rs, src/bin/nomic.rs, src/bitcoin/checkpoint.rs, src/bitcoin/header_queue.rs, src/bitcoin/mod.rs
This PR makes the code state-format compatible with both the currently running version of stakenet and testnet, by adding a `testnet` feature.
=> Cross-network state compatibility

Cargo.lock, Cargo.toml, build.rs, build.sh, rest/Cargo.lock
Patch release for currently deployed testnet in preparation for 5.2 upgrade.
=> Testnet 5.1.2

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, build.rs, build.sh, networks/testnet.toml, rest/Cargo.lock, src/app.rs, src/bin/nomic.rs, src/incentives.rs, src/network.rs, wasm/src/lib.rs, wasm/src/types.rs
Staging for testnet release 5.2.
=> Testnet 5.2

src/bitcoin/checkpoint.rs, src/bitcoin/mod.rs, src/bitcoin/signer.rs, src/bitcoin/threshold_sig.rs
This PR allows signatories to add their signatures to completed checkpoints.
=> Allow signing completed checkpoints

Cargo.lock, Cargo.toml, rest/Cargo.lock, src/airdrop.rs, src/app.rs, src/app/migrations.rs, src/bitcoin/checkpoint.rs, src/bitcoin/header_queue.rs, src/bitcoin/mod.rs, src/incentives.rs
This PR prunes all legacy state format fields, and upgrades to a version of orga which has done the same.
=> Post v6 cleanup

Cargo.lock, Cargo.toml, rest/Cargo.lock, src/app.rs, src/bin/nomic.rs, src/bitcoin/mod.rs
This PR adds direct withdrawals (aka interchain withdrawals) via the memo field of incoming NBTC transfers.
=> Direct withdrawals

Cargo.lock, Cargo.toml, networks/testnet.toml, rest/Cargo.lock, src/app.rs, src/bin/nomic.rs, src/bitcoin/checkpoint.rs, src/bitcoin/mod.rs, src/network.rs
This release enables the emergency disbursal, Interchain Deposits and Withdrawals, and many other significant bridge improvements.
=> Testnet 6.1

Cargo.lock, Cargo.toml, rest/Cargo.lock, src/bitcoin/checkpoint.rs
This PR fixes performance issues and signer issues.
=> Testnet patch 6.1.4

Cargo.lock, Cargo.toml, rest/Cargo.lock, src/app.rs, src/bin/nomic.rs
This PR updates to a new version of the Orga IBC module.
=> IBC update

src/bitcoin/checkpoint.rs, src/utils.rs, tests/bitcoin.rs, tests/node.rs
=> Revert "Submitting out-of-bounds checkpoint signature test"

Cargo.lock, Cargo.toml, src/bin/nomic.rs
This PR bumps Orga and updates the gRPC command to use the app's chain ID.
=> gRPC update

src/bitcoin/relayer.rs
Populates the relayer `/sigset` response with correctly set fees and deposit status.
=> Relayer address server fee values

src/bin/nomic.rs
This improves the service relaunch loop by using a query against the current version rather than a local store read. This also fixes the crashes seen in the signer and relayer due to this flaky check.
=> Fix service relaunching and signer crash

Cargo.lock, Cargo.toml, networks/testnet.toml, rest/Cargo.lock, src/bin/nomic.rs, src/bitcoin/checkpoint.rs, src/bitcoin/mod.rs
This PR prepares for the testnet 6.3 release.
=> Testnet 6.3 staging

Cargo.lock, Cargo.toml, networks/testnet.toml, rest/Cargo.lock
=> Testnet 6.4

Cargo.lock, Cargo.toml, networks/testnet.toml, rest/Cargo.lock, src/cosmos.rs
Fixes a typo in the config of 6.4.0.
=> Testnet 6.4.1

src/bitcoin/signer.rs
This PR fixes the signer exporter label names, and adds a checkpoint creation time timestamp.
=> Signer exporter

Cargo.lock, Cargo.toml, networks/testnet.toml, rest/Cargo.lock, src/app.rs, src/bin/nomic.rs
=> Testnet 6.5

Cargo.lock, Cargo.toml, rest/Cargo.lock, src/app.rs, src/app/migrations.rs, src/bin/nomic.rs
=> Testnet 6.6
