README.md
When no `external_address` or `laddr` is specified in `config.toml`, the node will not be discoverable if introspection fails, as the default laddr IP is set to 0.0.0.0:26656 - this guides a node operator to set it.
For me, on Debian 11 without UPnP, introspection to determine my external IP either doesn't work, or doesn't persist - this probably needs to be fixed (in informalsystems/tendermint-rs?) 
Until then, this workaround seems to do it.
=> doc: add instruction to specify external_address

Cargo.lock
Upgrading orga, to upgrade abci2, to increase the maximum ABCI message size to support large state sync chunks.
=> Update Cargo.lock for orga upgrade

Cargo.lock, Cargo.toml, src/airdrop.rs, src/app.rs, src/app/migrations.rs, src/bin/nomic.rs, src/bitcoin/adapter.rs, src/bitcoin/checkpoint.rs, src/bitcoin/header_queue.rs, src/bitcoin/mod.rs, src/bitcoin/threshold_sig.rs
This PR adds an `export` CLI subcommand to dump entire state as JSON which can be inspected for QA and debugging, and can be diffed with states exported from earlier versions to ensure migrations happened correctly.
This PR is blocking on https://github.com/nomic-io/orga/pull/173 being merged.
=> Migration QA

Cargo.lock, Cargo.toml, rest/Cargo.lock, src/airdrop.rs, src/app.rs, src/app/migrations.rs, src/bin/nomic.rs, src/bitcoin/adapter.rs, src/bitcoin/checkpoint.rs, src/bitcoin/header_queue.rs, src/bitcoin/mod.rs, src/bitcoin/signatory.rs, src/bitcoin/threshold_sig.rs, src/lib.rs
This PR updates the migration implementations for recent changes in orga.
=> Update migrations for new migration flow

Cargo.lock, Cargo.toml, networks/testnet.toml, rest/Cargo.lock
This hotfix patch upgrades Orga to fix an issue where nodes which had gone through a previous migration were skipping the migration step for subsequent upgrades.
=> Migrate fix

Cargo.lock, Cargo.toml, src/app.rs
This PR restricts network upgrade activation to a predictable time window.
=> Upgrade time window

src/app.rs, src/bitcoin/checkpoint.rs, src/bitcoin/mod.rs
This PR changes the emergency disbursal process to support outputs from outside the Bitcoin module (eg. NBTC on remote chains in the near future).
=> External disbursal outputs

Cargo.lock, Cargo.toml, build.rs, build.sh, networks/testnet.toml, rest/Cargo.lock, rest/src/main.rs, src/app.rs, src/bin/nomic.rs, src/bitcoin/header_queue.rs, src/network.rs, src/utils.rs, tests/node_spawn.rs, wasm/src/lib.rs
This PR improves the CLI and systems related to node spawning:
- Build legacy node and write it to binary store so nodes fresh nodes can start while an upgrade is happening, and nodes can be guaranteed to have all required fixes when upgrading without having to do multiple build steps
- Run legacy binary for all subcommands when network hasn't yet upgraded
- Exit signer and relayer when a node migration is detected, so they can move to the updated binary
- Allow using node config for all subcommands
- Remove remaining uses of `CHAIN_ID` constant
- Add various test options
- Changed `legacy_version` config option to a semver req rather than an exact string match
- Fix missing Tokio runtime for `--signal-version`
- Various tweaks making node config more robust
=> Validator UX / node management improvements

Cargo.lock, Cargo.toml, rest/Cargo.lock, src/bin/nomic.rs
Fixes check for whether to run legacy bin for nodes that have never undergone a migration.
=> Legacy bin fix

rest/src/main.rs, src/bin/nomic.rs, src/bitcoin/checkpoint.rs, src/bitcoin/relayer.rs, src/lib.rs, src/network.rs, src/utils.rs, tests/bitcoin.rs
Support `--node` in CLI commands, defaulting to `localhost:26657`. A future change should also make the default check the Tendermint config to support nonstandard ports automatically.
=> Support specifying RPC address via --node in CLI commands

src/bitcoin/checkpoint.rs, src/bitcoin/mod.rs, src/bitcoin/relayer.rs, src/utils.rs, tests/bitcoin.rs
This PR fixes the relayer getting stuck on chains with sufficiently large checkpoint queues (the proofs were previously exceeding Tendermint's maximum query size).
=> Limit number of checkpoints in queries

Cargo.toml, src/bitcoin/checkpoint.rs, src/bitcoin/signer.rs, src/utils.rs, tests/bitcoin.rs, wasm/src/lib.rs
This PR removes the default emergency disbursal redeem path. A recovery address is now required to be included in the emergency disbursal. All funds not protected by a recovery address will be paid back to the signatory set of the Nomic checkpoint that generated the emergency disbursal and will be recoverable by users after further validator coordination.
=> Default disbursal path removal

Cargo.lock, Cargo.toml, src/app.rs, src/bitcoin/checkpoint.rs, src/bitcoin/mod.rs
This PR adds offline signatory handling. Validators with offline signers are jailed after 20 consecutive missed checkpoints.
=> Offline signer handling

src/app.rs, src/bin/nomic.rs, src/bitcoin/checkpoint.rs, src/bitcoin/mod.rs, src/bitcoin/relayer.rs, src/utils.rs, tests/bitcoin.rs, wasm/src/lib.rs
NBTC transfers and deposits previously were processed instantly, creating a divergence between account balances and the most recently signed emergency disbursal. This PR changes movements of NBTC to only be processed once the next checkpoint is signed, so that all NBTC (other than dust accounts) is always backed by emergency disbursal outputs.
=> Process NBTC deposits and transfers after including checkpoint is signed

src/bitcoin/signer.rs
This is a simple fix for the signer in the specific case where there are less than `CHECKPOINT_WINDOW` checkpoints due to pruning.
=> Signer fix

src/app.rs
This PR separates stakenet from testnet upgrade activations to activate Wednesdays at 17:00 - 17:10 UTC to provide more predictable activation windows.
=> Change stakenet upgrades to activate Wednesdays

src/app.rs
This PR adds support for paying fees with nBTC instead of NOM for IBC message relaying and validator declaration.
=> nBTC call fees

Cargo.lock, Cargo.toml, rest/Cargo.lock, src/app.rs, src/bin/nomic.rs, src/bitcoin/checkpoint.rs, src/bitcoin/mod.rs, src/bitcoin/threshold_sig.rs, src/cosmos.rs, src/lib.rs
This PR adds emergency disbursal for nBTC on remote chains. In the event of an emergency disbursal, funds can be recovered by the validator set of the chain to which the nBTC was transferred.
=> Remote chain emergency disbursal

Cargo.toml, rest/Cargo.lock, src/app.rs, src/bin/nomic.rs, src/bitcoin/checkpoint.rs, src/bitcoin/mod.rs, src/bitcoin/relayer.rs, src/bitcoin/signer.rs, tests/bitcoin.rs
This PR adjusts the Bitcoin fee rate based on whether or not checkpoints were included into Bitcoin blocks, and enables a capacity limit to prevent depositing to certain signatory sets.
=> Adjust Bitcoin fee rate and enable capacity limit

Cargo.lock, Cargo.toml, rest/Cargo.lock
This PR upgrades to a version of orga with backported performance fixes - namely moving from on-disk checkpoints to in-memory snapshots for recent historical queryable states. This should fix observed issues relating to missed signatures.
=> Stakenet performance fix

src/bitcoin/relayer.rs
The relayer was not submitting proofs of checkpoint confirmation since it was searching from the oldest unconfirmed, but only looking back 100 blocks. We don't want to always use the newest unconfirmed since it is a moving target and on an active network there is likely always a tip which is unconfirmed - as a middle ground we use the oldest unconfirmed at a maximum of 5 checkpoints behind the tip (this will need parameterizing in the future).
=> Limit scan depth for unconfirmed checkpoints

src/bin/nomic.rs, src/bitcoin/mod.rs, src/bitcoin/signer.rs, src/utils.rs, tests/bitcoin.rs
This PR adds the `--reset-limits-at-index` flag to `nomic signer`, changes the default signatory set and reserve size decrease limits from 4% to 10%, and improves the way the limits are checked.
=> Circuit breaker improvements

src/app.rs, src/bitcoin/checkpoint.rs, src/bitcoin/mod.rs
This PR adds an OP_RETURN output containing a timestamping commitment (committing to the Tendermint block hash of the block where the checkpoint advances to signing) as the second output for every checkpoint transaction. This hash can be used to bootstrap light clients and contains Merkle paths down to the Nomic state, which itself holds block hashes of other chains via their IBC clients.
=> Timestamping commitments

src/bitcoin/checkpoint.rs
This PR prevents the network from having runaway checkpoints if they are for some reason not being confirmed on Bitcoin (for example, there was a standardness or validity issue, fees were too low, relayers are having issues relaying the confirmations which is incorrectly driving up the fee rate, the Bitcoin network is having issues, etc.). We now properly reflect the issues by not processing transfers until the checkpoints can be confirmed.
=> Add max_unconfirmed_checkpoints parameter

src/bin/nomic.rs
This PR updates `nomic declare` to pay the declare fee with nBTC if the self-delegation amount is 0.
=> Declare with nBTC

networks/stakenet.toml, networks/testnet.toml, rest/Cargo.lock, src/bin/nomic.rs, src/network.rs
This PR adds a `--btc-relayer` option for the `deposit` and `interchain-deposit` subcommands, and allows them to be configured in the network config.
=> Add bitcoin relayer addresses to network config

Cargo.lock, Cargo.toml, rest/Cargo.lock, src/bitcoin/threshold_sig.rs, src/cosmos.rs
This PR contains an already-released hotfix for a crash relating to invalid remote Cosmos chain operator keys, and a fix for the encoding format and migration for the `Pubkey` type. It also changes the op key relaying method to allow updating keys.
=> Op key fixes

src/bin/nomic.rs
This PR adds a `nomic signing-status` command to check which signatories are missing from the current signing checkpoint.
=> Signing status command

src/app.rs, src/bitcoin/threshold_sig.rs, src/cosmos.rs
Properly migrates versionless pubkey encodings, converting pubkeys to all include a version. After all networks have upgraded, this means we can get rid of the `Pubkey`/`VersionedPubkey` distinction.
=> Pubkey fix

Cargo.lock, Cargo.toml, rest/Cargo.lock, src/cosmos.rs
Lets the chain continue even when the `cosmos` state is inconsistent from the `ibc` state.
=> Missing cosmos client fix

Cargo.lock, Cargo.toml, rest/Cargo.lock, src/bin/nomic.rs, src/bitcoin/signer.rs, src/utils.rs, tests/bitcoin.rs
This PR adds an optional Prometheus exporter to the signer process, allowing for better monitoring of the signer. It can be enabled by passing `--prometheus-addr 127.0.0.1:1234`.
=> Signer Prometheus exporter

src/app.rs
This PR removes time and day-of-week restrictions on testnet upgrades, and changes stakenet to allow upgrades on all weekdays.
=> Upgrade windows

build.rs
This PR should slightly reduce legacy bin build times in the build script when a system RocksDB lib is specified through the `ROCKSDB_LIB_DIR` environment variable.
=> Forward ROCKSDB envvars through to build script legacy build

Cargo.lock, Cargo.toml, rest/Cargo.lock, src/bin/nomic.rs, src/network.rs
This PR adds patch `6.0.6`, which backports the default network selection and addition of `--network local` which is being introduced in `7.0.0`.
=> Stakenet 6 patches

Cargo.lock, Cargo.toml, rest/Cargo.lock, src/bitcoin/relayer.rs
Adds a response field for future-proofing threshold changes when deriving deposit addresses.
=> Add signatory threshold in relayer /sigset response
